export const LOGIN_FORM_UPDATE = 'FORM_UPDATE';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const PROFILE_FORM_UPDATE = 'PROFILE_FORM_UPDATE';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS,';
export const REPORT_FAILURE = 'REPORT_FAILURE';

export const ANECDOTES_FORM_UPDATE = 'ANECDOTES_FORM_UPDATE';
export const FETCH_ANECDOTES_SUCCESS = 'FETCH_ANECDOTES_SUCCESS';
export const CLEAR_ANECDOTES = 'CLEAR_ANECDOTES';
